name: Test Run All Benchmarks

on:
  workflow_dispatch:

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVKEY }}

    - name: Stop existing benchmarks and prepare environment
      run: |
        ssh -o StrictHostKeyChecking=no root@168.119.5.82 << 'EOF'
          set +e
          cd /root/benchmarks/benchmarks-data-demo
          ./stop.sh
          date=$(date +%Y-%m-%d)
          resultDir="results-$date"
          mkdir -p logs
          logFile="logs/$date.log"
          python3 ./update_time.py $date
          set -e
        EOF

    # - name: Run gas benchmarks
    #   run: |
    #     ssh -o StrictHostKeyChecking=no root@168.119.5.82 << 'EOF'
    #       set +e
    #       cd /root/benchmarks/gas-benchmarks
    #       date=$(date +%Y-%m-%d)
    #       resultDir="results-$date"
    #       logFile="logs/$date.log"
    #       cd gas-benchmarks
    #       git pull >> $logFile 2>&1
    #       ./run.sh \
    #         -t "tests/" \
    #         -w "warmup/warmup-1000bl-16wi-24tx.txt" \
    #         -c "nethermind,geth,reth,erigon,besu" \
    #         -r 1 \
    #         -o $resultDir >> $logFile 2>&1
    #       cp $resultDir/reports/index.html ../gas-data-demo/gas/$date.html
    #       cp $resultDir/reports/result.json ../gas-data-demo/gas/$date.json
    #       set -e
    #     EOF

    - name: Run genesis init speed benchmarks
      run: |
        ssh -o StrictHostKeyChecking=no root@168.119.5.82 << 'EOF'
          set +e
          cd /root/benchmarks/genesis-init-benchmarks
          date=$(date +%Y-%m-%d)
          resultDir="results-$date"
          logFile="logs/$date.log"
          cd genesis-init-benchmarks
          git pull >> $logFile 2>&1
          ./runSpeed.sh \
            -t "tests/" \
            -c "nethermind,reth,besu" \
            -r 1 \
            -o "$resultDir/speed" \
            -s 1,10 >> $logFile 2>&1
          cp $resultDir/speed/reports/speed.html ../gas-data-demo/genesis-init-memory/$date.html
          cp $resultDir/speed/reports/speed.json ../gas-data-demo/genesis-init-memory/$date.json
          set -e
        EOF

    - name: Run genesis init memory benchmarks
      run: |
        ssh -o StrictHostKeyChecking=no root@168.119.5.82 << 'EOF'
          set +e
          cd /root/benchmarks/genesis-init-benchmarks
          date=$(date +%Y-%m-%d)
          resultDir="results-$date"
          logFile="logs/$date.log"
          cd genesis-init-benchmarks
          ./runMemory.sh \
            -t "tests/" \
            -c "nethermind,reth,besu" \
            -r 1 \
            -o "$resultDir/memory" \
            -s 1,10 >> $logFile 2>&1
          cp $resultDir/memory/reports/memory.html ../gas-data-demo/genesis-init-memory/$date.html
          cp $resultDir/memory/reports/memory.json ../gas-data-demo/genesis-init-memory/$date.json
          set -e
        EOF

    - name: Run burntpix benchmarks
      run: |
        ssh -o StrictHostKeyChecking=no root@168.119.5.82 << 'EOF'
          set +e
          cd /root/benchmarks/burntpix-benchmarks
          date=$(date +%Y-%m-%d)
          resultDir="results-$date"
          logFile="logs/$date.log"
          cd burntpix-benchmarks
          git pull
          ./run.sh \
            -t "testburnt/" \
            -w "./testburntwarm/warm.txt" \
            -c "nethermind,reth,besu" \
            -r 1 \
            -o $resultDir >> $logFile 2>&1
          cp $resultDir/reports/index.html ../gas-data-demo/burntpix/$date.html
          cp $resultDir/reports/result.json ../gas-data-demo/burntpix/$date.json
          set -e
        EOF

    - name: Push results
      run: |
        ssh -o StrictHostKeyChecking=no root@168.119.5.82 << 'EOF'
          set +e
          cd /root/benchmarks/benchmarks-data-demo
          date=$(date +%Y-%m-%d)
          logFile="logs/$date.log"
          ./push.sh
          set -e
        EOF