name: Run Benchmarks

on:
  workflow_dispatch:
    inputs:
      root_dir:
        description: 'Enter the root directory for benchmarks'
        required: true
        default: '/root/benchmarks/'
      task:
        description: 'Select the task to run'
        required: true
        default: 'Run all'
        type: choice
        options:
          - Run all
          - Run gas benchmarks
          - Run genesis init speed benchmarks
          - Run genesis init memory benchmarks
          - Run burntpix benchmarks
      date:
        description: 'Enter a specific date (optional, format: YYYY-MM-DD)'
        required: false
        default: ''
      clients:
        description: 'Enter clients to use (JSON array format, e.g., ["nethermind","geth","reth","erigon","besu"])'
        required: true
        default: '["nethermind"]'
      sizes:
        description: 'Enter sizes (JSON array format, e.g., [1,10,100,500,1000])'
        required: false
        default: '[1]'
      repetitions:
        description: 'Enter the number of repetitions'
        required: true
        default: 1

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.set-date.outputs.date }}
      root_dir: ${{ steps.create-outputs.outputs.root_dir }}
      repetitions: ${{ steps.create-outputs.outputs.repetitions }}
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVKEY }}

    - name: Set DATE variable
      id: set-date
      run: |
        if [ -z "${{ github.event.inputs.date }}" ]; then
          DATE=$(date +%Y-%m-%d)
        else
          DATE=${{ github.event.inputs.date }}
        fi
        echo "DATE=$DATE" >> $GITHUB_ENV

  stop-existing-benchmarks:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVKEY }}

    - name: Stop existing benchmarks and prepare environment
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            -o ServerAliveCountMax=60 \
            root@${{ secrets.REMOTE_IP }} << 'EOF'
          set +e
          echo "============== Stop existing benchmarks and prepare environment =============="
          echo $DATE
          cd ${{ github.event.inputs.root_dir }}/benchmarks-data-demo
          ./stop.sh
          python3 ./update_time.py $DATE
          cat ./date.json
          set -e
        EOF

  run-gas-benchmarks:
    runs-on: ubuntu-latest
    needs: stop-existing-benchmarks
    if: ${{ github.event.inputs.task == 'Run gas benchmarks' || github.event.inputs.task == 'Run all' }}
    strategy:
      matrix:
        client: ${{ fromJson(github.event.inputs.clients) }}
        size: ${{ fromJson(github.event.inputs.sizes) }}
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVKEY }}

    - name: Run gas benchmarks
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            -o ServerAliveCountMax=60 \
            root@${{ secrets.REMOTE_IP }} << 'EOF'
          set +e
          cd ${{ github.event.inputs.root_dir }}/gas-benchmarks
          resultDir="results-$DATE"
          mkdir -p logs
          logFile="logs/$DATE.log"
          git pull
          ./run.sh \
            -t "tests3/" \
            -w "warmup/warmup-1000bl-16wi-24tx.txt" \
            -c "${{ matrix.client }}" \
            -r ${{ github.event.inputs.repetitions }} \
            -o $resultDir
          python3 report_metadata.py $DATE
          cp $resultDir/reports/index.html ../benchmarks-data-demo/gas/$DATE.html
          cp $resultDir/reports/result.json ../benchmarks-data-demo/gas/$DATE.json
          cp $resultDir/reports/metadata.json ../benchmarks-data-demo/gas/$DATE.metadata.json
          set -e
        EOF

  run-genesis-init-speed-benchmarks:
    runs-on: ubuntu-latest
    needs: run-gas-benchmarks
    if: ${{ github.event.inputs.task == 'Run genesis init speed benchmarks' || github.event.inputs.task == 'Run all' }}
    strategy:
      matrix:
        client: ${{ fromJson(github.event.inputs.clients) }}
        size: ${{ fromJson(github.event.inputs.sizes) }}
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVKEY }}

    - name: Run genesis init speed benchmarks
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            -o ServerAliveCountMax=60 \
            root@${{ secrets.REMOTE_IP }} << 'EOF'
          set +e
          echo "============== Running genesis init speed benchmarks =============="
          echo $DATE
          cd ${{ github.event.inputs.root_dir }}/genesis-init-benchmarks
          resultDir="results-$DATE"
          mkdir -p speed-logs
          logFile="speed-logs/$DATE.log"
          git pull
          ./runSpeed.sh \
            -t "tests/" \
            -c "${{ matrix.client }}" \
            -r ${{ github.event.inputs.repetitions }} \
            -o "$resultDir/speed" \
            -s "${{ matrix.size }}"
          python3 report_metadata.py $DATE speed
          cp $resultDir/speed/reports/speed.html ../benchmarks-data-demo/genesis-init-speed/$DATE.html
          cp $resultDir/speed/reports/speed.json ../benchmarks-data-demo/genesis-init-speed/$DATE.json
          cp $resultDir/speed/reports/metadata.json ../benchmarks-data-demo/genesis-init-speed/$DATE.metadata.json
          set -e
        EOF

  run-genesis-init-memory-benchmarks:
    runs-on: ubuntu-latest
    needs: run-genesis-init-speed-benchmarks
    if: ${{ github.event.inputs.task == 'Run genesis init memory benchmarks' || github.event.inputs.task == 'Run all' }}
    strategy:
      matrix:
        client: ${{ fromJson(github.event.inputs.clients) }}
        size: ${{ fromJson(github.event.inputs.sizes) }}
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVKEY }}

    - name: Run genesis init memory benchmarks
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            -o ServerAliveCountMax=60 \
            root@${{ secrets.REMOTE_IP }} << 'EOF'
          set +e
          cd ${{ github.event.inputs.root_dir }}/genesis-init-benchmarks
          resultDir="results-$DATE"
          mkdir -p memory-logs
          logFile="memory-logs/$DATE.log"
          git pull
          ./runMemory.sh \
            -t "tests/" \
            -c "${{ matrix.client }}" \
            -r ${{ github.event.inputs.repetitions }} \
            -o "$resultDir/memory" \
            -s "${{ matrix.size }}"
          python3 report_metadata.py $DATE memory
          cp $resultDir/memory/reports/memory.html ../benchmarks-data-demo/genesis-init-memory/$DATE.html
          cp $resultDir/memory/reports/memory.json ../benchmarks-data-demo/genesis-init-memory/$DATE.json
          needs.setup-environment.outputs.date }}.metadata.json
          set -e
        EOF

  run-burntpix-benchmarks:
    runs-on: ubuntu-latest
    needs: run-genesis-init-memory-benchmarks
    if: ${{ github.event.inputs.task == 'Run burntpix benchmarks' || github.event.inputs.task == 'Run all' }}
    strategy:
      matrix:
        client: ${{ fromJson(github.event.inputs.clients) }}
        size: ${{ fromJson(github.event.inputs.sizes) }}
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVKEY }}

    - name: Run burntpix benchmarks
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            -o ServerAliveCountMax=60 \
            root@${{ secrets.REMOTE_IP }} << 'EOF'
          set +e
          cd ${{ github.event.inputs.root_dir }}/burntpix-benchmarks
          resultDir="results-$DATE"
          mkdir -p logs
          logFile="logs/$DATE.log"
          git pull
          ./run.sh \
            -t "testburnt/" \
            -w "./testburntwarm/warm.txt" \
            -c "${{ matrix.client }}" \
            -r ${{ github.event.inputs.repetitions }} \
            -o $resultDir
          python3 report_metadata.py $DATE
          cp $resultDir/reports/index.html ../benchmarks-data-demo/burntpix/$DATE.html
          cp $resultDir/reports/result.json ../benchmarks-data-demo/burntpix/$DATE.json
          cp $resultDir/reports/metadata.json ../benchmarks-data-demo/burntpix/$DATE.metadata.json
          set -e
        EOF

  push-results:
    runs-on: ubuntu-latest
    needs: run-burntpix-benchmarks
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVKEY }}

    - name: Push results
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            -o ServerAliveCountMax=60 \
            root@${{ secrets.REMOTE_IP }} << 'EOF'
          set +e
          cd ${{ github.event.inputs.root_dir }}/benchmarks-data-demo
          git status
          ./push.sh
          set -e
        EOF