name: Test Run All Benchmarks

on:
  workflow_dispatch:

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVKEY }}

    - name: Execute benchmark commands on server
      run: |
        ssh -o StrictHostKeyChecking=no root@168.119.5.82 << 'EOF'
          cd /root/benchmarks/benchmarks-data-demo
          cd ../

          date=$(date +%Y-%m-%d)
          resultDir="results-$date"
          python3 ./update_time.py $date

          cd gas-benchmarks
          ./run.sh \
            -t "tests/" \
            -w "warmup/warmup-1000bl-16wi-24tx.txt" \
            -c "nethermind,geth,reth,erigon,besu" \
            -r 1 \
            -o $resultDir
          ./stop.sh
          cp $resultDir/reports/index.html ../gas-data-demo/gas/$date.html
          cp $resultDir/reports/result.json ../gas-data-demo/gas/$date.json

          cd ../genesis-init-benchmarks
          ./runSpeed.sh \
            -t "tests/" \
            -c "nethermind,reth,besu" \
            -r 1 \
            -o "$resultDir/speed" \
            -s 1,10
          ./stop.sh
          cp $resultDir/speed/reports/speed.html ../gas-data-demo/genesis-init-memory/$date.html
          cp $resultDir/speed/reports/speed.json ../gas-data-demo/genesis-init-memory/$date.json

          ./runMemory.sh \
            -t "tests/" \
            -c "nethermind,reth,besu" \
            -r 1 \
            -o "$resultDir/memory" \
            -s 1,10
          ./stop.sh
          cp $resultDir/memory/reports/memory.html ../gas-data-demo/genesis-init-memory/$date.html
          cp $resultDir/memory/reports/memory.json ../gas-data-demo/genesis-init-memory/$date.json

          cd ../burntpix-benchmarks
          ./run.sh \
            -t "testburnt/" \
            -w "./testburntwarm/warm.txt" \
            -c "nethermind,reth,besu" \
            -r 1 \
            -o $resultDir
          ./stop.sh
          cp $resultDir/reports/index.html ../gas-data-demo/burntpix/$date.html
          cp $resultDir/reports/result.json ../gas-data-demo/burntpix/$date.json

          cd ../gas-data-demo
          ./push.sh
        EOF